spin_manifest_version = "1"
authors = ["lug__aman"]
description = "this is a just demo project of spin"
name = "http-go-sample-test"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "http-go-sample-test"
source = "main.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
